// -*- C++ -*-
/**
 * @file    dancex11_configurator_export.h
 * @author  Martin Corino
 *
 * @brief   Generated
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DANCEX11_CONFIGURATOR_EXPORT_H
#define DANCEX11_CONFIGURATOR_EXPORT_H

#include "tao/x11/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS) && !defined (DANCE_CONFIGURATOR_HAS_DLL)
#  define DANCE_CONFIGURATOR_HAS_DLL 0
#endif /* TAOX11_AS_STATIC_LIBS && DANCE_CONFIGURATOR_HAS_DLL */

#if !defined (DANCE_CONFIGURATOR_HAS_DLL)
#  define DANCE_CONFIGURATOR_HAS_DLL 1
#endif /* ! DANCE_CONFIGURATOR_HAS_DLL */

#if defined (DANCE_CONFIGURATOR_HAS_DLL) && (DANCE_CONFIGURATOR_HAS_DLL == 1)
#  if defined (DANCE_CONFIGURATOR_BUILD_DLL)
#    define DAnCE_Configurator_Export TAOX11_Proper_Export_Flag
#    define DANCE_CONFIGURATOR_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define DANCE_CONFIGURATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DANCE_CONFIGURATOR_BUILD_DLL */
#    define DAnCE_Configurator_Export TAOX11_Proper_Import_Flag
#    define DANCE_CONFIGURATOR_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define DANCE_CONFIGURATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DANCE_CONFIGURATOR_BUILD_DLL */
#else /* DANCE_CONFIGURATOR_HAS_DLL == 1 */
#  define DAnCE_Configurator_Export
#  define DANCE_CONFIGURATOR_SINGLETON_DECLARATION(T)
#  define DANCE_CONFIGURATOR_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DANCE_CONFIGURATOR_HAS_DLL == 1 */

#endif /* DANCEX11_CONFIGURATOR_EXPORT_H */
