/**
 * @file    dynany_handler_export.h
 * @author  Marijke Hengstmengel
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DYNANY_HANDLER_EXPORT_H
#define DYNANY_HANDLER_EXPORT_H

#include "tao/x11/taox11_export_macros.h"

#if !defined (DYNANY_HANDLER_HAS_DLL)
#  define DYNANY_HANDLER_HAS_DLL 1
#endif /* ! DYNANY_HANDLER_HAS_DLL */

#if defined (DYNANY_HANDLER_HAS_DLL) && (DYNANY_HANDLER_HAS_DLL == 1)
#  if defined (DYNANY_HANDLER_BUILD_DLL)
#    define DynAny_Handler_Export TAOX11_Proper_Export_Flag
#    define DYNANY_HANDLER_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define DYNANY_HANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DYNANY_HANDLER_BUILD_DLL */
#    define DynAny_Handler_Export TAOX11_Proper_Import_Flag
#    define DYNANY_HANDLER_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define DYNANY_HANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DYNANY_HANDLER_BUILD_DLL */
#else /* DYNANY_HANDLER_HAS_DLL == 1 */
#  define DynAny_Handler_Export
#  define DYNANY_HANDLER_SINGLETON_DECLARATION(T)
#  define DYNANY_HANDLER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DYNANY_HANDLER_HAS_DLL == 1 */

#endif /* DYNANY_HANDLER_EXPORT_H */

