// -*- C++ -*-
/**
 * @file    dancex11_deployment_cdrplanloader_export.h
 * @author  Martin Corino
 *
 * @brief   Generated
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef _DANCEX11_DEPLOYMENT_CDRPLANLOADER_EXPORT_H_EXPORT_INCLUDED__
#define _DANCEX11_DEPLOYMENT_CDRPLANLOADER_EXPORT_H_EXPORT_INCLUDED__

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (DANCEX11_CDRPLAN_LOADER_HAS_DLL)
#  define DANCEX11_CDRPLAN_LOADER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && DANCEX11_CDRPLAN_LOADER_HAS_DLL */

#if !defined (DANCEX11_CDRPLAN_LOADER_HAS_DLL)
#  define DANCEX11_CDRPLAN_LOADER_HAS_DLL 1
#endif /* ! DANCEX11_CDRPLAN_LOADER_HAS_DLL */

#if defined (DANCEX11_CDRPLAN_LOADER_HAS_DLL) && (DANCEX11_CDRPLAN_LOADER_HAS_DLL == 1)
#  if defined (DANCEX11_CDRPLAN_LOADER_BUILD_DLL)
#    define DANCEX11_CDRPLAN_LOADER_Export ACE_Proper_Export_Flag
#    define DANCEX11_CDRPLAN_LOADER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define DANCEX11_CDRPLAN_LOADER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* DANCEX11_CDRPLAN_LOADER_BUILD_DLL */
#    define DANCEX11_CDRPLAN_LOADER_Export ACE_Proper_Import_Flag
#    define DANCEX11_CDRPLAN_LOADER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define DANCEX11_CDRPLAN_LOADER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* DANCEX11_CDRPLAN_LOADER_BUILD_DLL */
#else /* DANCEX11_CDRPLAN_LOADER_HAS_DLL == 1 */
#  define DANCEX11_CDRPLAN_LOADER_Export
#  define DANCEX11_CDRPLAN_LOADER_SINGLETON_DECLARATION(T)
#  define DANCEX11_CDRPLAN_LOADER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* DANCEX11_CDRPLAN_LOADER_HAS_DLL == 1 */

#endif /* _DANCEX11_DEPLOYMENT_CDRPLANLOADER_EXPORT_H_EXPORT_INCLUDED__ */
