/**
 * @file    deployment_invalidproperty.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef DEPLOYMENT_INVALIDPROPERTY_IDL
#define DEPLOYMENT_INVALIDPROPERTY_IDL

module Deployment {
  exception InvalidProperty {
    string name;
    string reason;
  };
};

#endif
