/**
 * @file    deployment_stoperror.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DEPLOYMENT_STOPERROR_IDL
#define DEPLOYMENT_STOPERROR_IDL

module Deployment {
  exception StopError {
    string name;
    string reason;
  };
};
#endif /* DEPLOYMENT_STOPERROR_IDL */

