/**
 * @file    deployment_invalidcomponentexecparameter.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DEPLOYMENT_INVALIDCOMPONENTEXECPARAMETER_IDL
#define DEPLOYMENT_INVALIDCOMPONENTEXECPARAMETER_IDL

module Deployment {
  exception InvalidComponentExecParameter {
    string name;
    string reason;
  };
};

#endif
