/**
 * @file    deployment_planerror.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DEPLOYMENT_PLANERROR_IDL
#define DEPLOYMENT_PLANERROR_IDL

module Deployment {
  exception PlanError {
    string name;
    string reason;
  };
};

#endif /* DEPLOYMENT_PLANERROR_IDL */
