include::_{backend}_settings.adoc[]

= _Deployment Plan_ descriptors

== Locality Instance descriptor

=== Introduction

This descriptor provides the configuration for a Locality Manager
instance as a set of D&C Component Implementation, Instance,
LocalityConstraint and Artifact descriptions for a _Deployment Plan_.

Although the LM is not a Component as such DnCX11 allows the definition
of LM instances in a way similar to regular components to be able to
configure runtime settings, locality constraints and provide lifecycle
interception points.

Declaring Locality Instance descriptors is optional. In case none are
declared DnCX11 will use default definitions for any LM instances
required in the deployment of a plan.

=== Definition

A Locality Manager Instance descriptor is defined as follows:

----------------------------------
{lm-instance-key} {lm-instance-id}
    [ {deployment-node} ]
    [ {deployment-location} ]
    [ {deployment-artifacts} ]
    [ {deployment-properties} ]
----------------------------------

Where

* \{lm-instance-key} := `nl.remedy.it.DnCX11.LocalityManager`
* \{lm-instance-id} :=
<<{parent_dir}/config-plan.adoc#dotted-identifier,dotted-identifier>>
* \{deployment-node} := a <<config-other.adoc#_deployment_node_descriptor,Deployment Node
descriptor>>
* \{deployment-location} := a
<<config-other.adoc#_deployment_locality_descriptor,Deployment Locality descriptor>>
* \{deployment-artifacts} := a sequence of zero or more
<<config-artifact.adoc#,Deployment Artifact descriptors>>
* \{deployment-properties} := a sequence of zero or more
<<config-properties.adoc#_deployment_property_descriptors,Deployment Property
descriptors>>

The order in which the nested descriptors appear in an actual
declaration is not prescribed. Each declared (nested) descriptor must
however be complete before starting the declaration of another (nested
or toplevel) descriptor declaration.

The line breaks shown in the format definition above are not mandatory
but only there for display formatting purposes (newlines are simply
considered whitespace separating _CONFIG_ tokens).

=== Description

The `{lm-instance-id}` identifier specifies the name for the D&C
Instance description and should be unique in the context of the defined
_Deployment Plan_.

The DnCX11 _CONFIG_ loader will automatically identify a D&C
Implementation description for the defined LM instance using the
standard name `_AXCIOMA_LocalityManagerSvc_`. In case no Implementation
description with this name yet exists in the context of the defined plan
an new Implementation description with this name will be created.

Any explicitly declared ExecParameter property descriptors as part of
the optional `{deployment-properties}` for a LM Instance descriptor are
also added as _execParameter_ properties of the D&C Implementation
description created/used for the LM.

In the case of multiple LM Instance descriptor declarations the referred
Implementation description will be the same for each instance and
therefor explicit ExecParameter property descriptors are only required
on the first instance descriptor declaration.

In case the optional `{deployment-location}` descriptor is missing the
locality id for the define LM instance is assumed to be equal to the
name of the LM instance (i.e. `{lm-instance-id}`).

Based on the locality and node assignments for each instance description
in the plan one *SameProcess* _localityConstraint_ will be defined for
each combination of node and locality assignments listing all instances
(including LM instances) matching that combination. In addition a single
*DifferentProcess* _localityConstraint_s will be defined for each node
listing the first instances of each *SameProcess* constraint for that
node.

=== Example

The following descriptor declarations

----------------------------------------------------------------------------------------------------
# locality manager instance for locality "LocalityInstance1" on Node "LocalityOne"
nl.remedy.it.DnCX11.LocalityManager LocalityInstance1
    nl.remedy.it.DnCX11.Node "LocalityOne"
    nl.remedy.it.DnCX11.ConfigProperty nl.remedy.it.DnCX11.Locality.Arguments "-n LocalityInstance1"

# locality manager instance for locality "LocalityInstance2" on Node "LocalityTwo"
nl.remedy.it.DnCX11.LocalityManager LocalityInstance2
    nl.remedy.it.DnCX11.Node "LocalityTwo"
    nl.remedy.it.DnCX11.ConfigProperty nl.remedy.it.DnCX11.Locality.Arguments "-n LocalityInstance2"

----------------------------------------------------------------------------------------------------

would define one D&C Implementation description named
`LocalityManagerSvc` referred to by two D&C Instance descriptions:

.  with
* _name_ = `LocalityInstance1`
* _node_ = `LocalityOne`
* one _configProperty_ `nl.remedy.it.DnCX11.Locality.Arguments` with
value `"-n LocalityInstance1"`
.  with
* _name_ = `LocalityInstance2`
* _node_ = `LocalityTwo`
* one _configProperty_ `nl.remedy.it.DnCX11.Locality.Arguments` with
value `"-n LocalityInstance2"`

As explicit `{deployment-locality}` descriptors declarations are absent
the locality assignments for the two instances are assumed to be
`LocalityInstance1` for the first instance and `LocalityInstance2` for
the second.
