include::_{backend}_settings.adoc[]

= DnCX11 tool configuration descriptors

== Instance Deployment Handler descriptor

=== Introduction

This descriptor provides the configuration for an _Instance Deployment
Handler_ (IDH) plugin to be loaded as part of the DnCX11 tool runtime
environment.
See <<../dncx11-config#_instance_deployment_handlers,here>> for more information.

=== Definition

An IDH descriptor is defined as follows:

-------------------------------------------------------------------------------------------------------
{idh-descriptor-key} {idh-artifact} {idh-factory} [ {deployment-openmode} ] [ {deployment-properties} ]
-------------------------------------------------------------------------------------------------------

Where

* \{idh-descriptor-key} := `nl.remedy.it.DnCX11.InstanceHandler`
* \{idh-artifact} := <<{parent_dir}/config-plan.adoc#identifier,identifier>>
* \{idh-factory} := <<{parent_dir}/config-plan.adoc#identifier,identifier>>
* \{deployment-openmode} := integer
<<{parent_dir}/config-plan.adoc#value,literal value>>
* \{deployment-properties} := a sequence of zero or more
<<config-properties.adoc#_deployment_property_descriptors,Deployment Property
descriptors>>

=== Description

The `{idh-artifact}` identifier specifies the implementation artifact
(library) from which the IDH object can be instantiated. The format of
this identifier depends on the deployment runtime platform for which the
plugin is configured. For the current DnCX11 deployment tool runtime
environment this should be a shared library name compatible with the ACE
DLL loader, i.e. without path, without platform dependent prefix (f.i.
'lib') and without extension(s).

The `{idh-factory}` identifier specifies the factory (method) with which
the IDH object can be instantiated from the loaded artifact. The format
of this identifier depends on the deployment runtime platform for which
the plugin is configured.

The *optional* `{deployment-openmode}` integer literal specifies an
artifact loader dependent flag value. For the current DnCX11 deployment
tool runtime environment this should be a shared library openmode value
as used by the ACE DLL loader. It is normally not necessary to specify
this value.

=== Example

The following descriptor declaration

------------------------------------------------------------------------------------------------
# DnCX11 standard CIAOX11 component instantiation plugin
nl.remedy.it.DnCX11.InstanceHandler ciaox11_deployment_handlers create_CIAOX11_Component_Handler
------------------------------------------------------------------------------------------------

would direct the DnCX11 deployment runtime to load the shared library
specified by `ciaox11_deployment_handlers` (resulting in
`libciaox11_deployment_handlers.so` on Linux and
`ciaox11_deployment_handlers.dll` on Windows) and instantiate an IDH
object by calling the `void` method `create_CIAOX11_Component_Handler`
which must return an IDH reference.
