/**
 * @file    config_handlers_export.h
 * @author  Marijke Hengstmengel
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef CONFIG_HANDLERS_EXPORT_H
#define CONFIG_HANDLERS_EXPORT_H

#include "tao/x11/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS) && !defined (CONFIG_HANDLERS_HAS_DLL)
#  define CONFIG_HANDLERS_HAS_DLL 0
#endif /* TAOX11_AS_STATIC_LIBS && CONFIG_HANDLERS_HAS_DLL */

#if !defined (CONFIG_HANDLERS_HAS_DLL)
#  define CONFIG_HANDLERS_HAS_DLL 1
#endif /* ! CONFIG_HANDLERS_HAS_DLL */

#if defined (CONFIG_HANDLERS_HAS_DLL) && (CONFIG_HANDLERS_HAS_DLL == 1)
#  if defined (CONFIG_HANDLERS_BUILD_DLL)
#    define Config_Handlers_Export TAOX11_Proper_Export_Flag
#    define CONFIG_HANDLERS_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define CONFIG_HANDLERS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* CONFIG_HANDLERS_BUILD_DLL */
#    define Config_Handlers_Export TAOX11_Proper_Import_Flag
#    define CONFIG_HANDLERS_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define CONFIG_HANDLERS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* CONFIG_HANDLERS_BUILD_DLL */
#else /* CONFIG_HANDLERS_HAS_DLL == 1 */
#  define Config_Handlers_Export
#  define CONFIG_HANDLERS_SINGLETON_DECLARATION(T)
#  define CONFIG_HANDLERS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* CONFIG_HANDLERS_HAS_DLL == 1 */

#endif /* CONFIG_HANDLERS_EXPORT_H */

