// -*- C++ -*-
/**
 * @file    installation_repository_manager_export.h
 * @author  Martin Corino
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DANCEX11_INSTALLATION_REPOSITORY_MANAGER_EXPORT_H
#define DANCEX11_INSTALLATION_REPOSITORY_MANAGER_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL)
#  define INSTALLATION_REPOSITORY_MANAGER_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && INSTALLATION_REPOSITORY_MANAGER_HAS_DLL */

#if !defined (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL)
#  define INSTALLATION_REPOSITORY_MANAGER_HAS_DLL 1
#endif /* ! INSTALLATION_REPOSITORY_MANAGER_HAS_DLL */

#if defined (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL) && (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL == 1)
#  if defined (INSTALLATION_REPOSITORY_MANAGER_BUILD_DLL)
#    define Installation_Repository_Manager_Export ACE_Proper_Export_Flag
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* INSTALLATION_REPOSITORY_MANAGER_BUILD_DLL */
#    define Installation_Repository_Manager_Export ACE_Proper_Import_Flag
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* INSTALLATION_REPOSITORY_MANAGER_BUILD_DLL */
#else /* INSTALLATION_REPOSITORY_MANAGER_HAS_DLL == 1 */
#  define Installation_Repository_Manager_Export
#  define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARATION(T)
#  define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* INSTALLATION_REPOSITORY_MANAGER_HAS_DLL == 1 */

#endif /* DANCEX11_INSTALLATION_REPOSITORY_MANAGER_EXPORT_H */

// End of auto generated file.
