// -*- C++ -*-
/**
 * @file    installation_repository_manager_export.h
 * @author  Martin Corino
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef DANCEX11_INSTALLATION_REPOSITORY_MANAGER_EXPORT_H
#define DANCEX11_INSTALLATION_REPOSITORY_MANAGER_EXPORT_H

#include "tao/x11/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS) && !defined (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL)
#  define INSTALLATION_REPOSITORY_MANAGER_HAS_DLL 0
#endif /* TAOX11_AS_STATIC_LIBS && INSTALLATION_REPOSITORY_MANAGER_HAS_DLL */

#if !defined (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL)
#  define INSTALLATION_REPOSITORY_MANAGER_HAS_DLL 1
#endif /* ! INSTALLATION_REPOSITORY_MANAGER_HAS_DLL */

#if defined (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL) && (INSTALLATION_REPOSITORY_MANAGER_HAS_DLL == 1)
#  if defined (INSTALLATION_REPOSITORY_MANAGER_BUILD_DLL)
#    define Installation_Repository_Manager_Export TAOX11_Proper_Export_Flag
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* INSTALLATION_REPOSITORY_MANAGER_BUILD_DLL */
#    define Installation_Repository_Manager_Export TAOX11_Proper_Import_Flag
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* INSTALLATION_REPOSITORY_MANAGER_BUILD_DLL */
#else /* INSTALLATION_REPOSITORY_MANAGER_HAS_DLL == 1 */
#  define Installation_Repository_Manager_Export
#  define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARATION(T)
#  define INSTALLATION_REPOSITORY_MANAGER_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* INSTALLATION_REPOSITORY_MANAGER_HAS_DLL == 1 */

#endif /* DANCEX11_INSTALLATION_REPOSITORY_MANAGER_EXPORT_H */

